// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/acetimego/zonedbtesting/tzfiles
//     --output_dir /home/brian/src/acetimego/zonedbtesting
//     --tz_version 2023d
//     --actions zonedb
//     --languages go
//     --scope complete
//     --db_namespace zonedbtesting
//     --include_list include_list.txt
//     --start_year 1980
//     --until_year 2200
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2023d
//
// Supported Zones: 5 (4 zones, 1 links)
// Unsupported Zones: 591 (347 zones, 244 links)
//
// Requested Years: [1980,2200]
// Accurate Years: [1980,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1967,2012]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1967,2024]
// Max Buffer Size: 6
//
// Records:
//   Infos: 5
//   Eras: 5
//   Policies: 2
//   Rules: 13
//
// Memory:
//   Rules: 156
//   Policies: 8
//   Eras: 70
//   Zones: 48
//   Links: 12
//   Registry: 0
//   Formats: 38
//   Letters: 7
//   Fragments: 0
//   Names: 77
//   TOTAL: 416
//
// DO NOT EDIT

package zonedbtesting

import (
	"github.com/bxparks/acetimego/zoneinfo"
)
// ---------------------------------------------------------------------------
// ZoneRuleRecords is a concatenated array of zoneinfo.ZoneInfoRecord objects
// from all ZonePolicyRecords.
//
// Supported zone policies: 2
// numRules: 13
// ---------------------------------------------------------------------------

var ZoneRuleRecords = []zoneinfo.ZoneRuleRecord{
	// ---------------------------------------------------------------------------
	// PolicyName: US
	// RuleIndex: 0
	// RuleCount: 7
	// ---------------------------------------------------------------------------

	// Anchor: Rule    US    1967    2006    -    Oct    lastSun    2:00    0    S
	{
		FromYear: -32767,
		ToYear: -32767,
		InMonth: 1,
		OnDayOfWeek: 0,
		OnDayOfMonth: 1,
		AtSecondsCode: 0, // 0 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 0,
		LetterIndex: 2, // "S"
	},
	// Rule    US    1967    2006    -    Oct    lastSun    2:00    0    S
	{
		FromYear: 1967,
		ToYear: 2006,
		InMonth: 10,
		OnDayOfWeek: 7,
		OnDayOfMonth: 0,
		AtSecondsCode: 480, // 7200 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 0,
		LetterIndex: 2, // "S"
	},
	// Rule    US    1975    only    -    Feb    lastSun    2:00    1:00    D
	{
		FromYear: 1975,
		ToYear: 1975,
		InMonth: 2,
		OnDayOfWeek: 7,
		OnDayOfMonth: 0,
		AtSecondsCode: 480, // 7200 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 60,
		LetterIndex: 1, // "D"
	},
	// Rule    US    1976    1986    -    Apr    lastSun    2:00    1:00    D
	{
		FromYear: 1976,
		ToYear: 1986,
		InMonth: 4,
		OnDayOfWeek: 7,
		OnDayOfMonth: 0,
		AtSecondsCode: 480, // 7200 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 60,
		LetterIndex: 1, // "D"
	},
	// Rule    US    1987    2006    -    Apr    Sun>=1    2:00    1:00    D
	{
		FromYear: 1987,
		ToYear: 2006,
		InMonth: 4,
		OnDayOfWeek: 7,
		OnDayOfMonth: 1,
		AtSecondsCode: 480, // 7200 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 60,
		LetterIndex: 1, // "D"
	},
	// Rule    US    2007    max    -    Mar    Sun>=8    2:00    1:00    D
	{
		FromYear: 2007,
		ToYear: 32766,
		InMonth: 3,
		OnDayOfWeek: 7,
		OnDayOfMonth: 8,
		AtSecondsCode: 480, // 7200 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 60,
		LetterIndex: 1, // "D"
	},
	// Rule    US    2007    max    -    Nov    Sun>=1    2:00    0    S
	{
		FromYear: 2007,
		ToYear: 32766,
		InMonth: 11,
		OnDayOfWeek: 7,
		OnDayOfMonth: 1,
		AtSecondsCode: 480, // 7200 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 0,
		LetterIndex: 2, // "S"
	},

	// ---------------------------------------------------------------------------
	// PolicyName: WS
	// RuleIndex: 7
	// RuleCount: 6
	// ---------------------------------------------------------------------------

	// Anchor: Rule    WS    2011    only    -    Apr    Sat>=1    4:00    0    -
	{
		FromYear: -32767,
		ToYear: -32767,
		InMonth: 1,
		OnDayOfWeek: 0,
		OnDayOfMonth: 1,
		AtSecondsCode: 0, // 0 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 0,
		LetterIndex: 0, // ""
	},
	// Rule    WS    2010    only    -    Sep    lastSun    0:00    1    -
	{
		FromYear: 2010,
		ToYear: 2010,
		InMonth: 9,
		OnDayOfWeek: 7,
		OnDayOfMonth: 0,
		AtSecondsCode: 0, // 0 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 60,
		LetterIndex: 0, // ""
	},
	// Rule    WS    2011    only    -    Apr    Sat>=1    4:00    0    -
	{
		FromYear: 2011,
		ToYear: 2011,
		InMonth: 4,
		OnDayOfWeek: 6,
		OnDayOfMonth: 1,
		AtSecondsCode: 960, // 14400 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 0,
		LetterIndex: 0, // ""
	},
	// Rule    WS    2011    only    -    Sep    lastSat    3:00    1    -
	{
		FromYear: 2011,
		ToYear: 2011,
		InMonth: 9,
		OnDayOfWeek: 6,
		OnDayOfMonth: 0,
		AtSecondsCode: 720, // 10800 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 60,
		LetterIndex: 0, // ""
	},
	// Rule    WS    2012    2021    -    Apr    Sun>=1    4:00    0    -
	{
		FromYear: 2012,
		ToYear: 2021,
		InMonth: 4,
		OnDayOfWeek: 7,
		OnDayOfMonth: 1,
		AtSecondsCode: 960, // 14400 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 0,
		LetterIndex: 0, // ""
	},
	// Rule    WS    2012    2020    -    Sep    lastSun    3:00    1    -
	{
		FromYear: 2012,
		ToYear: 2020,
		InMonth: 9,
		OnDayOfWeek: 7,
		OnDayOfMonth: 0,
		AtSecondsCode: 720, // 10800 / 15
		AtSecondsModifier: 0, // SuffixW + remainder=0
		DeltaMinutes: 60,
		LetterIndex: 0, // ""
	},


}

// ---------------------------------------------------------------------------
// ZonePolicyRecords contain indexes into the ZoneRuleRecords.
// Supported zone policies: 2
// ---------------------------------------------------------------------------

var ZonePolicyRecords = []zoneinfo.ZonePolicyRecord{
	{RuleIndex: 0, RuleCount: 0}, // 0: PolicyName: (None)
	{RuleIndex: 0, RuleCount: 7}, // 1: PolicyName: US
	{RuleIndex: 7, RuleCount: 6}, // 2: PolicyName: WS

}

