// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/acetimego/zonedbtesting/tzfiles
//     --output_dir /home/brian/src/acetimego/zonedbtesting
//     --tz_version 2024b
//     --actions zonedb
//     --languages go
//     --scope complete
//     --db_namespace zonedbtesting
//     --include_list include_list.txt
//     --start_year 1980
//     --until_year 2200
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2024b
//
// Supported Zones: 5 (4 zones, 1 links)
// Unsupported Zones: 591 (335 zones, 256 links)
//
// Requested Years: [1980,2200]
// Accurate Years: [1980,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1967,2012]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1967,2024]
// Max Buffer Size: 6
//
// Records:
//   Infos: 5
//   Eras: 5
//   Policies: 2
//   Rules: 13
//
// Memory:
//   Rules: 156
//   Policies: 8
//   Eras: 70
//   Zones: 48
//   Links: 12
//   Registry: 0
//   Formats: 24
//   Letters: 7
//   Fragments: 0
//   Names: 77
//   TOTAL: 402
//
// DO NOT EDIT

package zonedbtesting

// ---------------------------------------------------------------------------
// String constants.
// ---------------------------------------------------------------------------

// All ZoneRule.Letter entries concatenated together.
const LetterData = "" +
	"D" +
	"S" +
	"~"

// Byte offset into LetterData for each index. The actual Letter string
// at index `i` given by the `ZoneRule.Letter` field is
// `LetterData[LetterOffsets[i]:LetterOffsets[i+1]]`.
var LetterOffsets = []uint8{
	0, 0, 1, 2,
}

// ---------------------------------------------------------------------------
// ZoneRulesData is the encoded version of ZoneRuleRecords in
// zone_policies_test.go. It contains an array of
// ZoneRuleRecord encoded as string.
//
// Supported zone policies: 2
// numRules: 13
// ---------------------------------------------------------------------------

const ZoneRuleCount = 13

const ZoneRuleChunkSize = 12

// ZoneRulesData contains the ZoneRuleRecords data as a hex encoded string.
const ZoneRulesData = "\x01\x80\x01\x80\x01\x00\x01\x00\x00\x00\x00\x02" +
	"\xaf\x07\xd6\x07\x0a\x07\x00\x00\xe0\x01\x00\x02" +
	"\xb7\x07\xb7\x07\x02\x07\x00\x00\xe0\x01\x3c\x01" +
	"\xb8\x07\xc2\x07\x04\x07\x00\x00\xe0\x01\x3c\x01" +
	"\xc3\x07\xd6\x07\x04\x07\x01\x00\xe0\x01\x3c\x01" +
	"\xd7\x07\xfe\x7f\x03\x07\x08\x00\xe0\x01\x3c\x01" +
	"\xd7\x07\xfe\x7f\x0b\x07\x01\x00\xe0\x01\x00\x02" +
	"\x01\x80\x01\x80\x01\x00\x01\x00\x00\x00\x00\x00" +
	"\xda\x07\xda\x07\x09\x07\x00\x00\x00\x00\x3c\x00" +
	"\xdb\x07\xdb\x07\x04\x06\x01\x00\xc0\x03\x00\x00" +
	"\xdb\x07\xdb\x07\x09\x06\x00\x00\xd0\x02\x3c\x00" +
	"\xdc\x07\xe5\x07\x04\x07\x01\x00\xc0\x03\x00\x00" +
	"\xdc\x07\xe4\x07\x09\x07\x00\x00\xd0\x02\x3c\x00"

// ---------------------------------------------------------------------------
// ZonePoliciesData is the encoded version of ZonePolicyRecords in
// zone_policies_test.go. It contains an array of
// ZonePolicyRecord which is a pair of (index, count) into the ZoneRuleRecords
// array.
//
// Supported zone policies: 2
// ---------------------------------------------------------------------------

const ZonePolicyCount = 3

const ZonePolicyChunkSize = 4

// ZonePoliciesData contains the ZonePolicyRecords data as a hex encoded string.
const ZonePoliciesData = "\x00\x00\x00\x00" +
	"\x00\x00\x07\x00" +
	"\x07\x00\x06\x00"

// ---------------------------------------------------------------------------
// Unsupported zone policies: 132
// ---------------------------------------------------------------------------

// AN {unused}
// AQ {unused}
// AS {unused}
// AT {unused}
// AV {unused}
// AW {unused}
// Albania {unused}
// Algeria {unused}
// Arg {unused}
// Armenia {unused}
// Aus {unused}
// Austria {unused}
// Azer {unused}
// Barb {unused}
// Belgium {unused}
// Belize {unused}
// Bermuda {unused}
// Brazil {unused}
// Bulg {unused}
// C-Eur {unused}
// CA {unused}
// CO {unused}
// CR {unused}
// Canada {unused}
// Chatham {unused}
// Chicago {unused}
// Chile {unused}
// Cook {unused}
// Cuba {unused}
// Cyprus {unused}
// Czech {unused}
// DR {unused}
// Denver {unused}
// Detroit {unused}
// Dhaka {unused}
// E-Eur {unused}
// E-EurAsia {unused}
// EU {unused}
// EUAsia {unused}
// Ecuador {unused}
// Edm {unused}
// Egypt {unused}
// EgyptAsia {unused}
// Eire {unused}
// Falk {unused}
// Fiji {unused}
// Finland {unused}
// France {unused}
// GB-Eire {unused}
// Germany {unused}
// Greece {unused}
// Guam {unused}
// Guat {unused}
// HK {unused}
// Haiti {unused}
// Halifax {unused}
// Holiday {unused}
// Hond {unused}
// Hungary {unused}
// Indianapolis {unused}
// Iran {unused}
// Iraq {unused}
// Italy {unused}
// Japan {unused}
// Jordan {unused}
// Kyrgyz {unused}
// LH {unused}
// Latvia {unused}
// Lebanon {unused}
// Libya {unused}
// Louisville {unused}
// Macau {unused}
// Malta {unused}
// Marengo {unused}
// Mauritius {unused}
// Menominee {unused}
// Mexico {unused}
// Moldova {unused}
// Moncton {unused}
// Mongol {unused}
// Morocco {unused}
// NBorneo {unused}
// NC {unused}
// NT_YK {unused}
// NYC {unused}
// NZ {unused}
// Namibia {unused}
// Nic {unused}
// PRC {unused}
// Pakistan {unused}
// Palestine {unused}
// Para {unused}
// Perry {unused}
// Peru {unused}
// Phil {unused}
// Pike {unused}
// Poland {unused}
// Port {unused}
// Pulaski {unused}
// ROK {unused}
// Regina {unused}
// Romania {unused}
// Russia {unused}
// RussiaAsia {unused}
// SA {unused}
// Salv {unused}
// SanLuis {unused}
// Shang {unused}
// SovietZone {unused}
// Spain {unused}
// SpainAfrica {unused}
// StJohns {unused}
// Starke {unused}
// Sudan {unused}
// Swift {unused}
// Swiss {unused}
// Syria {unused}
// Taiwan {unused}
// Thule {unused}
// Tonga {unused}
// Toronto {unused}
// Troll {unused}
// Tunisia {unused}
// Turkey {unused}
// Uruguay {unused}
// Vanc {unused}
// Vanuatu {unused}
// Vincennes {unused}
// W-Eur {unused}
// Winn {unused}
// Yukon {unused}
// Zion {unused}


// ---------------------------------------------------------------------------
// Notable zone policies: 0
// ---------------------------------------------------------------------------


