name: Go Verify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # We should use the `tinygo` image, but there's a permission problem with
    # it. The `tinygo-dev` image seems to work.
    container: ghcr.io/tinygo-org/tinygo-dev

    steps:
    - name: Check Go Versions
      run: |
        go version
        tinygo version

    # See comment in https://github.com/bxparks/playgroundgo
    - name: Fix Git Permission Error
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Checkout AceTimeGo
      uses: actions/checkout@v3

    - name: Build
      run: |
        make build buildtiny

    - name: Test
      run: |
        make test testtiny
