name: Go Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout AceTimeGo
      uses: actions/checkout@v3

    - name: Checkout Go language
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Tests
      run: |
        make test

    - name: Cmds
      run: |
        make -C cmd build
